# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: States
    url: 'states/'
    weight: 20
  - name: Constituencies
    url: 'constituencies/'
    weight: 30
  - name: Members
    url: 'members/'
    weight: 40
  - name: Documents
    url: 'documents/'
    weight: 50
